name: BERNARD ROS2 Package Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test-x86:
    runs-on: ubuntu-22.04

    container:
      image: ros:humble-ros-base

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install deps
        run: |
          apt-get update
          apt-get install -y libusb-1.0-0-dev

      - name: Build
        run: bash buildPackage.bash humble Debug

      - name: Test
        shell: bash
        run: |
          source install/setup.bash
          ./build/bernard_hw_if/test_actuators_node

  build-and-test-arm64:
    runs-on: ubuntu-22.04-arm

    container:
      image: ros:humble-ros-base

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install deps
        run: |
          apt-get update
          apt-get install -y libusb-1.0-0-dev
      
      - name: Build
        run: bash buildPackage.bash humble Debug

      - name: Test
        shell: bash
        run: |
          source install/setup.bash
          ./build/bernard_hw_if/test_actuators_node